name: Lighthouse for PR
on: [pull_request]
    # branches:
      # - 'ci/*'
      # - 'feat/**'
  #     - 'fix/**'
  #     - 'chore/**'
  #     - 'refactor/**'
  #     - 'build/**'

jobs:
  lighthouse_main:
    runs-on: ubuntu-latest
    # Github Actions default timeout-minutes are insanely high and we pay for that
    # If it takes more than 8 minutes, it most likely already failed without a exit condition
    timeout-minutes: 8
    steps:
      - name: show branch names
        shell: bash
        run: echo ${{GITHUB_REF}}
      - name: âœ… Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: ðŸŸ© Use Node.js 16.3.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.3.0'
